print(" ------------------------------------------------")
print("|                                                |")
print("|    06WhileLoop                                 |")
print("|    Name : Aimen Rehan                          |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
subject = input("What is the name of this subject ")
while subject != "IST":
  print("Not Correct - try again ")
  subject = input("What is the name of this subject ")
if subject == "IST":
  print("")
  print("")
  print("Congratulations!!")
  print("")
  print("")
  print("")
